version: '3.8'

services:
  smb-server:
    image: ubuntu:22.04
    container_name: smb-server
    volumes:
      - smb_data:/shared
      - ./smb.conf:/etc/samba/smb.conf
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "137-139:137-139"
      - "445:445"
    command: /bin/bash /entrypoint.sh
    healthcheck:
      test: ["CMD", "smbclient", "-L", "localhost", "-U", "user%password"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-service
    volumes:
      - smb_data:/mnt/shared
    devices:
      - /dev/bus/usb:/dev/bus/usb
    depends_on:
      smb-server:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - SMB_HOST=smb-server
      - SMB_SHARE=shared
      - SMB_USER=user
      - SMB_PASSWORD=password
    privileged: true

volumes:
  smb_data:

networks:
  app-network:
    driver: bridge